<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="version.xsl"?>

<!DOCTYPE versioninfo [
<!ELEMENT versioninfo (version*)>
<!ELEMENT version (relname,reltype,reltypename,relnum,subtype,relsvnum,fullrel,fullname)>
<!ELEMENT relname (#PCDATA)>
<!ELEMENT reltype (#PCDATA)>
<!ELEMENT reltypename (#PCDATA)>
<!ELEMENT relnum (#PCDATA)>
<!ELEMENT subtype (#PCDATA)>
<!ELEMENT relsvnum (#PCDATA)>
<!ELEMENT fullrel (#PCDATA)>
<!ELEMENT fullname (#PCDATA)>
]>

<versioninfo>

<version>
<relname>iDB</relname>
<reltype>Al</reltype>
<reltypename>Alpha</reltypename>
<relnum>0.6.4</relnum>
<subtype>SVN</subtype>
<relsvnum>992</relsvnum>
<fullrel>iDB Al 0.6.4</fullrel>
<fullname>iDB Al 0.6.4 SVN 992</fullname>
</version>

</versioninfo>
